### ISSUE TITLE
Eror Issue / missing Path Filed

### ISSUE THREAD

**Issue by Rivalakmalll** [mateonunez/website#358]
hi i like your project from this repo but  i have problems i cant find /images/profile.jpg in my file i want change in can you say the detail file location?  thx

**Comment by mateonunez** [comment]
Hey @Rivalakmalll, thank you for the appreciation! 

You can find the image picture right here: `public/images/profile.jpg`

**Comment by Rivalakmalll** [comment]
Im alrd found the file but the file only show dot.png

**Comment by mateonunez** [comment]
Have you set correctly your `.env` file with the localhost url?

**Comment by Rivalakmalll** [comment]
hei pal can you help me to deploy on vercel when im try to deploy i got this eror i need some help ASAP
 <html>
<body>


TypeError: fetch failed
--
19:15:38.229 | at Object.fetch (node:internal/deps/undici/undici:11576:11)
19:15:38.229 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
19:15:38.230 | cause: Error: connect ECONNREFUSED 127.0.0.1:3000
19:15:38.230 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
19:15:38.230 | at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
19:15:38.230 | errno: -111,
19:15:38.230 | code: 'ECONNREFUSED',
19:15:38.231 | syscall: 'connect',
19:15:38.231 | address: '127.0.0.1',
19:15:38.231 | port: 3000
19:15:38.231 | }
19:15:38.231 | }
19:15:38.232 | TypeError: Cannot read properties of undefined (reading 'json')
19:15:38.233 | at profileFetcher (/vercel/path0/.next/server/app/open-source/page.js:411:41)
19:15:38.233 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
19:15:38.233 | at async OpenSourcePage (/vercel/path0/.next/server/app/open-source/page.js:472:21)
19:15:38.244 |  
19:15:38.244 | Error occurred prerendering page "/open-source". Read more: https://nextjs.org/docs/messages/prerender-error
19:15:38.244 | TypeError: Cannot read properties of undefined (reading 'json')
19:15:38.245 | at profileFetcher (/vercel/path0/.next/server/app/open-source/page.js:411:41)
19:15:38.245 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
19:15:38.245 | at async OpenSourcePage (/vercel/path0/.next/server/app/open-source/page.js:472:21)
19:15:38.285 | TypeError: fetch failed
19:15:38.290 | at Object.fetch (node:internal/deps/undici/undici:11576:11)
19:15:38.291 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
19:15:38.291 | cause: Error: connect ECONNREFUSED 127.0.0.1:3000
19:15:38.291 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
19:15:38.291 | at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
19:15:38.291 | errno: -111,
19:15:38.291 | code: 'ECONNREFUSED',
19:15:38.291 | syscall: 'connect',
19:15:38.291 | address: '127.0.0.1',
19:15:38.291 | port: 3000
19:15:38.291 | }
19:15:38.291 | }
19:15:38.296 |  
19:15:38.296 | Error occurred prerendering page "/spotify". Read more: https://nextjs.org/docs/messages/prerender-error
19:15:38.296 | TypeError: fetch failed
19:15:38.296 | at Object.fetch (node:internal/deps/undici/undici:11576:11)
19:15:38.296 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
19:15:38.297 | - info Generating static pages (13/13)
19:15:38.302 |  
19:15:38.303 | > Export encountered errors on following paths:
19:15:38.303 | /open-source/page: /open-source
19:15:38.303 | /spotify/page: /spotify
19:15:38.363 | error Command failed with exit code 1.
19:15:38.365 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
19:15:38.386 | Error: Command "yarn run build" exited with 1


</body>
</html>

**Comment by mateonunez** [comment]
Can you send me more information about you environment?

node version
npm/yarn/pnpm version
SO 
etc

Thanks!

**Comment by Rivalakmalll** [comment]
ok but i want know detail path file first? bcs there many same name  u want to know / see @mateonunez  give me detail path like from file .env or smtg

**Comment by mateonunez** [comment]
> ok but i want know detail path file first? bcs there many same name  u want to know / see @mateonunez  give me detail path like from file .env or smtg

Without technical details of the environment, etc it's really hard to give you a solution.

Please, provide more details or just create a reproduction error.

**Comment by Rivalakmalll** [comment]
Ok let me send the detail for u see appreciate it
